# Generated by Django 3.0.8 on 2020-09-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=270)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.FileField(upload_to='uploads/')),
                ('product_type', models.CharField(choices=[('M', 'Misc'), ('B', 'Buttons')], max_length=1)),
                ('variation', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('sku', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('size', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(verbose_name='Created on')),
            ],
        ),
    ]
