# Generated by Django 3.1.1 on 2020-10-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=270)),
                ('featured', models.ImageField(upload_to='')),
                ('created_date', models.DateTimeField(verbose_name='Created on')),
            ],
        ),
    ]
