# Generated by Django 3.1.1 on 2020-10-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeCon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=270)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('eventTicets', models.URLField()),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(default='NowCreated on')),
            ],
        ),
    ]
