# Generated by Django 3.1.1 on 2020-10-01 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_animecon'),
        ('main_app', '0003_orderdetail'),
    ]

    operations = [
    ]
