# Generated by Django 3.0.8 on 2020-09-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200927_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fandom',
            field=models.CharField(choices=[('H', 'My Hero Academia'), ('M', 'Miraculous Lady'), ('S', 'Sailor Moon'), ('V', 'Vampire Hunter D'), ('J', "JoJo's Bizarre Adventure"), ('H', 'Haikyuu'), ('K', 'Kingdom Hearts'), ('N', 'Necahual'), ('F', 'Final Fantasy'), ('C', 'Castlevania')], default='C', max_length=1),
            preserve_default=False,
        ),
    ]
